/* CVS $Id: $ */
package ca.uqam.vocab.vivo; 
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /home/heon/01-SPRINT/2021-11-12-SPRINT-08/VivoStudioWS/ca.uqam.vivo.vocab/src/main/resources/vivo.nt 
 * @author Auto-generated by schemagen on 15 déc. 2021 14:57 
 */
public class VCARD {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/2006/vcard/ns#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    public static final Resource Acquaintance = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Acquaintance" );
    
    /** <p>To specify the components of the delivery address for the vCard object</p> */
    public static final Resource Address = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Address" );
    
    /** <p>These types are concerned with information related to the delivery addressing 
     *  or label for the vCard object</p>
     */
    public static final Resource Addressing = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Addressing" );
    
    public static final Resource Agent = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Agent" );
    
    public static final Resource Calendar = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Calendar" );
    
    /** <p>To specify the URI for the busy time associated with the object that the vCard 
     *  represents. Was called FBURI in vCard</p>
     */
    public static final Resource CalendarBusy = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#CalendarBusy" );
    
    /** <p>To specify the URI for a calendar associated with the object represented by 
     *  the vCard. Was called CALURI in vCard.</p>
     */
    public static final Resource CalendarLink = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#CalendarLink" );
    
    /** <p>To specify the calendar user address [RFC5545] to which a scheduling request 
     *  [RFC5546] should be sent for the object represented by the vCard. Was called 
     *  CALADRURI in vCard</p>
     */
    public static final Resource CalendarRequest = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#CalendarRequest" );
    
    /** <p>To specify application category information about the vCard, also known as 
     *  tags. This was called CATEGORIES in vCard.</p>
     */
    public static final Resource Category = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Category" );
    
    /** <p>Also called mobile telephone</p> */
    public static final Resource Cell = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Cell" );
    
    public static final Resource Child = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Child" );
    
    /** <p>Contains all the Code related Classes that are used to indicate vCard Types</p> */
    public static final Resource Code = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Code" );
    
    public static final Resource Colleague = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Colleague" );
    
    /** <p>These properties describe information about how to communicate with the object 
     *  the vCard represents</p>
     */
    public static final Resource Communication = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Communication" );
    
    public static final Resource Contact = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Contact" );
    
    public static final Resource Coresident = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Coresident" );
    
    public static final Resource Coworker = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Coworker" );
    
    public static final Resource Crush = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Crush" );
    
    public static final Resource Date = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Date" );
    
    /** <p>To specify the electronic mail address for communication with the object the 
     *  vCard represents</p>
     */
    public static final Resource Email = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Email" );
    
    public static final Resource Emergency = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Emergency" );
    
    /** <p>These properties are concerned with additional explanations, such as that 
     *  related to informational notes or revisions specific to the vCard</p>
     */
    public static final Resource Explanatory = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Explanatory" );
    
    public static final Resource Fax = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Fax" );
    
    public static final Resource Female = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Female" );
    
    /** <p>Specifies the formatted text corresponding to the name of the object the vCard 
     *  represents</p>
     */
    public static final Resource FormattedName = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#FormattedName" );
    
    public static final Resource Friend = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Friend" );
    
    public static final Resource Gender = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Gender" );
    
    /** <p>Used to indicate global positioning information that is specific to an address</p> */
    public static final Resource Geo = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Geo" );
    
    /** <p>These properties are concerned with information associated with geographical 
     *  positions or regions associated with the object the vCard represents</p>
     */
    public static final Resource Geographical = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Geographical" );
    
    /** <p>Defines all the properties required to be a Group of Individuals or Organizations</p> */
    public static final Resource Group = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Group" );
    
    /** <p>This implies that the property is related to an individual's personal life</p> */
    public static final Resource Home = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Home" );
    
    /** <p>These types are used to capture information associated with the identification 
     *  and naming of the entity associated with the vCard</p>
     */
    public static final Resource Identification = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Identification" );
    
    /** <p>Defines all the properties required to be an Individual</p> */
    public static final Resource Individual = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Individual" );
    
    /** <p>To specify the URI for instant messaging and presence protocol communications 
     *  with the object the vCard represents. Was called IMPP in vCard.</p>
     */
    public static final Resource InstantMessage = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#InstantMessage" );
    
    public static final Resource Key = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Key" );
    
    public static final Resource Kin = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Kin" );
    
    /** <p>The parent class for all vCard Objects</p> */
    public static final Resource Kind = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Kind" );
    
    /** <p>To specify the language(s) that may be used for contacting the entity associated 
     *  with the vCard.</p>
     */
    public static final Resource Language = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Language" );
    
    /** <p>Defines all the properties required to be a Location</p> */
    public static final Resource Location = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Location" );
    
    /** <p>To specify a graphic image of a logo associated with the object the vCard 
     *  represents</p>
     */
    public static final Resource Logo = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Logo" );
    
    public static final Resource Male = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Male" );
    
    public static final Resource Me = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Me" );
    
    public static final Resource Met = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Met" );
    
    public static final Resource Muse = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Muse" );
    
    /** <p>Specifies the components of the name of the object the vCard represents</p> */
    public static final Resource Name = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Name" );
    
    public static final Resource Neighbor = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Neighbor" );
    
    /** <p>Specifies the text corresponding to the nickname of the object the vCard represents</p> */
    public static final Resource Nickname = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Nickname" );
    
    public static final Resource None = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#None" );
    
    /** <p>To specify supplemental information or a comment that is associated with the 
     *  vCard</p>
     */
    public static final Resource Note = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Note" );
    
    /** <p>To specify the organizational name associated with the vCardDefines all the 
     *  properties required to be an Organization</p>
     */
    public static final Resource Organization = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Organization" );
    
    public static final Resource OrganizationName = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#OrganizationName" );
    
    public static final Resource OrganizationUnitName = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#OrganizationUnitName" );
    
    /** <p>These properties are concerned with information associated with characteristics 
     *  of the organization or organizational units of the object that the vCard represents</p>
     */
    public static final Resource Organizational = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Organizational" );
    
    public static final Resource Other = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Other" );
    
    public static final Resource Pager = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Pager" );
    
    public static final Resource Parent = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Parent" );
    
    /** <p>Specifies an image or photograph information that annotates some aspect of 
     *  the object the vCard represents</p>
     */
    public static final Resource Photo = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Photo" );
    
    /** <p>To specify a relationship between another entity and the entity represented 
     *  by this vCard</p>
     */
    public static final Resource Related = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Related" );
    
    public static final Resource RelatedType = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#RelatedType" );
    
    public static final Resource Role = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Role" );
    
    /** <p>Contains all the Security related Classes</p> */
    public static final Resource Security = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Security" );
    
    public static final Resource Sibling = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Sibling" );
    
    /** <p>To specify a digital sound content information that annotates some aspect 
     *  of the vCard. This property is often used to specify the proper pronunciation 
     *  of the name property value of the vCard</p>
     */
    public static final Resource Sound = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Sound" );
    
    public static final Resource Spouse = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Spouse" );
    
    public static final Resource Sweetheart = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Sweetheart" );
    
    public static final Resource Telephone = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Telephone" );
    
    public static final Resource TelephoneType = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#TelephoneType" );
    
    /** <p>Also called sms telephone</p> */
    public static final Resource Text = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Text" );
    
    public static final Resource TextPhone = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#TextPhone" );
    
    /** <p>Used to indicate time zone information that is specific to a location or address</p> */
    public static final Resource TimeZone = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#TimeZone" );
    
    /** <p>To specify the position or job of the object the vCard represents</p> */
    public static final Resource Title = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Title" );
    
    /** <p>This is called TYPE in vCard but renamed here to Context for less confusion 
     *  (with types/class)</p>
     */
    public static final Resource Type = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Type" );
    
    /** <p>To specify a uniform resource locator associated with the object to which 
     *  the vCard refers. Examples for individuals include personal web sites, blogs, 
     *  and social networking site identifiers.</p>
     */
    public static final Resource URL = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#URL" );
    
    public static final Resource Unknown = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Unknown" );
    
    public static final Resource Video = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Video" );
    
    public static final Resource Voice = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Voice" );
    
    /** <p>This implies that the property is related to an individual's work place</p> */
    public static final Resource Work = M_MODEL.createResource( "http://www.w3.org/2006/vcard/ns#Work" );
    
}
