/* CVS $Id: $ */
package ca.uqam.vocab.uqam; 
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;
 
/**
 * Vocabulary definitions from /home/heon/01-SPRINT/2021-11-12-SPRINT-08/VivoStudioWS2/VS-GIT/VIVO-DataConnect/bundles/ca.uqam.vivo.vocab/src/main/resources/UQAM_DATA.ttl 
 * @author Auto-generated by schemagen on 19 janv. 2022 17:11 
 */
public class UQAM_EVENT {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static final OntModel M_MODEL = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/vivo.uqam.ca/data/event#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "(c) 2022 Université du Québec à Montréal ; Auteur Michel Héon PhD";
    
    public static final OntClass id = M_MODEL.createClass( "http://purl.org/vivo.uqam.ca/data/event#id" );
    
}
